### ISSUE TITLE
Styling of website

### ISSUE THREAD

**Issue by peetucket** [sul-dlss-labs/srt#2]
References:

- https://projects.invisionapp.com/share/AM11CWNCZDNF#/screens/454150630
- https://projects.invisionapp.com/share/H9Z6ZGRTEFK#/screens/438179384
- https://drive.google.com/drive/u/1/folders/14OfzztK2V-rqBhheoJzba4j0cxqzZwoV

Home Page:
- [x] bullet list in top nav of home page should have circles instead of asterix
- [x] center text/images in "learn about system racism" and "get invovled" on home page
- [x] create entire lower section (below the fold) of the home page
- [x] setup proper rows on the home page so each row of content has the correct background color
- [x] add content to footer and style correctly
- [x] copy content from google doc where needed: https://docs.google.com/document/d/1BymGVywaU2U8hFw5xq_djALpvOEkUGXX1Vr4tMfAJQ8/edit#heading=h.mjaprv1vi6aq
- [ ] Adjust resource "bubble" boxes on home page to improve spacing

Subpages:
- [x] fix default template so it better matches the subpages
- [x] create other pages:
  - [x] housing
  - [x] policing
  - [x] collaborate
  - [x] connect
  - [x] about

General:
- [x] Double check colors with comp: https://projects.invisionapp.com/share/AM11CWNCZDNF#/screens/455263270
- [x] Adjust fonts to better match design comps
- [ ] Test on mobile browser, can we get images to collapse or hide on small widths?
- [x] Link text in footer and other pages
- [x] contact us form - how to do this?  see for example: https://medium.com/getform-all-about/how-to-add-a-contact-form-to-your-jekyll-website-6c61e811bdee
- [x] Remove links where there is no content (e.g. in the footer)
- [x] add favicon.ico

**Comment by astridu** [comment]
Thanks for taking a first pass at the website. It's looking good! Here are my comments by page:

Global:
Fonts
- All font should be Source Sans Pro sans serif, 
- body text = 14 pt, 
- H1 = 30 pt light, Color = 702421 (red)
- H2 = 21 pt bold,
- H3 = 18 pt bold
- on light backgrounds use black text, on dark backgrounds, use white text

Homepage
1. Text at the top right corner: 
- Use same color as logo: 0D1F2C
- 14pt bold italicized
3. Navigation should be center aligned on the page, Last links s/b 'Get Involved'
4. Add the 2nd box back in, but it has different text/button
5. Replace the other 2 buttons w/new buttons and new section headings (H1 = 21 pt bold)
![image](https://user-images.githubusercontent.com/42216982/128802188-d4fce381-bb1d-4f72-a4b3-546c7ced2f11.png)
6. For the Amanda Gorman quote, is there a way to use web text to display that rather than the image? The image is fuzzy. Is there a web font we could use that looks similar?
7. All text on dark backgrounds such as the blue should be white. Headings should be H1.
8. Use H2 for the headers on the beige background. 
9. 'About SRT' should be H1

Housing
1. Use H1 for 'Housing'
2. H2 for Latest research, Latest news, Resources
3. H3 for all section titles under Resources

Policing
1. Use H1 for 'Policing'
2. H2 for Latest research, Latest news, Resources
3. H3 for all section titles under Resources

Get Involved
1. Use H1 for 'Connect with the community'
2. Link to web form.
